### PR TITLE
Hallux and Persona Notebooks

### PR DESCRIPTION
**Pull request by johnstillman**
Here is my first pull request...  This should include the update to the table of contents as well.

### CODE REVIEW

**Comment by johnstillman** [comment]
Hopefully I am doing this correctly.  There are two notebooks, hallux and persona, as well as, a sql file in the contrib_data folder.

**Comment by johnstillman** [comment]
I added a couple png images to the persona notebook and some more docs into contrib_data.

**Comment by MLDERES** [comment]
@johnstillman , this is a great set of instructions, but I don't know that it works.  For instance, 'Entities' is referenced in the hallux notebook, but it isn't defined in that notebook.

I'd like a little more information on what "here we go" means.  Just a sentence which gives a little background as to what exactly is going to happen (you have the steps, but I'm not sure why these are there). 

The pictures give a great understanding of what is happening in the database.  Nice touch.

For those parts that are "under construction" what will they do eventually?  Specifying this in the notebook will be helpful.

**Comment by MLDERES** [comment]
Oh, and one last thing.  Since you reference a stored procedure in Hallux, it would be good to put the text of the stored procedure  text in your notebook as a reference.  You can put a code reference in a markdown box by surrounding with three tick symbols

```sql 
SELECT * 
FROM People
```

**Comment by johnstillman** [comment]
Sounds good

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by MLDERES — APPROVED** [review]

**Pull request merged**
